In [33]:
import pandas as pd

from mailsift.config import DATASETS_DIR

In [34]:
sources = ["CEAS_08", "Enron", "Ling", "SpamAssasin"]
frames = []
for source in sources:
    df = pd.read_csv(f"{DATASETS_DIR}/dataset-1/{source}.csv",
                     usecols=["subject", "body", "label"],
                     dtype={"subject": str, "body": str, "label": int},
                    #  nrows=2859
                     )
    print(f"{source}: {len(df)} emails")
    frames.append(df)

dataset = pd.concat(frames, ignore_index=True)
print(f"Total: {len(dataset)} emails")

CEAS_08: 39154 emails
Enron: 29767 emails
Ling: 2859 emails
SpamAssasin: 5809 emails
Total: 77589 emails

In [35]:
dataset

,subject,body,label
0,Never agree to be a loser,"Buck up, your troubles caused by small dimensi...",1
1,Befriend Jenna Jameson,\nUpgrade your sex and pleasures with these te...,1
2,CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...,1
3,Re: svn commit: r619753 - in /spamassassin/tru...,Would anyone object to removing .so from this ...,0
4,SpecialPricesPharmMoreinfo,\nWelcomeFastShippingCustomerSupport\nhttp://7...,1
...,...,...,...
77584,Busy? Home Study Makes Sense!,\n\n \n--- \n![](http://images.pcdi-homestud...,1
77585,Preferred Non-Smoker Rates for Smokers,This is a multi-part message in MIME format. -...,1
77586,"How to get 10,000 FREE hits per day to any web...","Dear Subscriber,\n\nIf I could show you a way ...",1
77587,Cannabis Difference,****Mid-Summer Customer Appreciation SALE!****...,1
77588,[ILUG] WILSON KAMELA,ATTN:SIR/MADAN \n\n ...,1

In [36]:
dataset["body"] = dataset["body"].fillna("")

dataset["body"] = dataset["body"].apply(lambda x : x.replace('\n', ' ').replace('\r', ' '))
dataset

,subject,body,label
0,Never agree to be a loser,"Buck up, your troubles caused by small dimensi...",1
1,Befriend Jenna Jameson,Upgrade your sex and pleasures with these tec...,1
2,CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...,1
3,Re: svn commit: r619753 - in /spamassassin/tru...,Would anyone object to removing .so from this ...,0
4,SpecialPricesPharmMoreinfo,WelcomeFastShippingCustomerSupport http://7iw...,1
...,...,...,...
77584,Busy? Home Study Makes Sense!,--- ![](http://images.pcdi-homestudy.co...,1
77585,Preferred Non-Smoker Rates for Smokers,This is a multi-part message in MIME format. -...,1
77586,"How to get 10,000 FREE hits per day to any web...","Dear Subscriber, If I could show you a way to...",1
77587,Cannabis Difference,****Mid-Summer Customer Appreciation SALE!****...,1
77588,[ILUG] WILSON KAMELA,ATTN:SIR/MADAN ST...,1

In [38]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 77589 entries, 0 to 77588
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   subject  77285 non-null  str
 1   body     77589 non-null  str
 2   label    77589 non-null  int64
dtypes: int64(1), str(2)
memory usage: 1.8 MB